version: "3.9"
services:
  spring-api:
    image: spring-api-image
    container_name: spring-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - spring-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://leandrorose:root@alkemyjava2clase6.1wqbsea.mongodb.net/?retryWrites=true&w=majority&appName=AlkemyJava2Clase6

networks:
  spring-network:
    driver: bridge
